name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18
        cache: pnpm
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake libvips-dev libmagick++-dev
    - name: Build
      run: pnpm install --frozen-lockfile --no-optional && pnpm run build

  darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install imagemagick vips node
        /usr/local/opt/node@18/bin/corepack enable
    - name: Build
      run: |
        export PATH="/usr/local/opt/node@18/bin:$PATH"
        pnpm install --frozen-lockfile --no-optional && pnpm run build

